---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# mmtable2

<!-- badges: start -->
<!-- badges: end -->

The goal of mmtable2 is to provide a ggplot2-like interface for untidy tables.
It does this by introducing algabraic untidy tables. 

## Installation

This probably to buggy for installation, but feel free to clone!

## Example

This is a basic example which shows you how to solve a common problem:

```{r example1, message=FALSE, warning=FALSE, include=FALSE}
# Load all packages
library(tibble)
library(gt)
library(tidyverse)
library(mmtable2)
# devtools::load_all()
# library(mmtable2)
# list.files("R",full.names = T) %>% map(source)
```

```{r example2, message=FALSE, warning=FALSE, include=FALSE}
# Source method /

`/.mmtable` <- function(mmtable1,mmtable2){

  # mmtable1 <- table1
  # mmtable2 <- table1

#  Get table 1 attributes
    # Give table_id_header
  attr(mmtable1,"_original_data") <- attr(mmtable1,"_original_data") %>% mutate(table_id_row = "Table 1")
    # Get header info
  header_info_1 <- attr(mmtable1,"_header_info")
  # Update header info
  header_info_1$row_header_df <- header_info_1$row_header_df %>% bind_rows(tibble(row_header_vars = "table_id_row", direction = "left_top"), .)
  attr(mmtable1,"_header_info") <- header_info_1


# Get table 2 attibutes
  attr(mmtable2,"_original_data") <- attr(mmtable2,"_original_data") %>% mutate(table_id_row = "Table 2")
  # Get header info
  header_info_2 <- attr(mmtable2,"_header_info")
  # Update header info
  header_info_2$row_header_df <- header_info_2$row_header_df %>% bind_rows(tibble(row_header_vars = "table_id_row", direction = "left_top"), .)
  attr(mmtable2,"_header_info") <- header_info_2

  mmtable1 * mmtable2

}

```

```{r example3, message=FALSE, warning=FALSE, include=FALSE}
# Source method +

`+.mmtable` <- function(mmtable1,mmtable2){

  # browser()

  # mmtable1 <- table1
  # mmtable2 <- table1

  if(is.null(mmtable2)){return(mmtable1)}


  if("mmtable_header" %in% class(mmtable2)){
    return(mmtable1 * mmtable2)
  }


  if("mmtable_table_item" %in% class(mmtable2)){
    # return(mmtable1 * mmtable2)

    return_table <- mmtable2(mmtable1,attr(mmtable2,"text"))

    return_table <- mmtable2(mmtable1,attr(mmtable2,"text"))

    class(return_table) <- append("mmtable",class(return_table))

    return(return_table)

      }

  #  Get table 1 attributes
  # Give table_id_header
  attr(mmtable1,"_original_data") <- attr(mmtable1,"_original_data") %>% mutate(table_id_col = "Table 1")
  # Get header info
  header_info_1 <- attr(mmtable1,"_header_info")
  # Update header info
  header_info_1$col_header_df <- header_info_1$col_header_df %>% bind_rows(tibble(col_header_vars = "table_id_col", direction = "top_left"), .)
  attr(mmtable1,"_header_info") <- header_info_1


  # Get table 2 attibutes
  attr(mmtable2,"_original_data") <- attr(mmtable2,"_original_data") %>% mutate(table_id_col = "Table 2")
  # Get header info
  header_info_2 <- attr(mmtable2,"_header_info")
  # Update header info
  header_info_2$col_header_df <- header_info_2$col_header_df %>% bind_rows(tibble(col_header_vars = "table_id_col", direction = "top_left"), .)
  attr(mmtable2,"_header_info") <- header_info_2

  attributes(mmtable1)
  attributes(mmtable2)

  mmtable1 * mmtable2


}

```

```{r example4, message=FALSE, warning=FALSE, include=FALSE}

# source method *

`*.mmtable` <-function(mmtable1,mmtable2){

  # browser()

  if(is.null(mmtable2)){return(mmtable1)}

  headers_1 <- attributes(mmtable1) %>% .[["_header_info"]]
  headers_2 <- attributes(mmtable2) %>% .[["_header_info"]]

  original_data_1 <- attributes(mmtable1) %>% .[["_original_data"]]
  original_data_2 <- attributes(mmtable2) %>% .[["_original_data"]]

  original_data <- bind_rows(original_data_2,original_data_1)

  col_header_df_1 <- headers_1$col_header_df %>% map_dfr(as.character)
  row_header_df_1 <- headers_1$row_header_df %>% map_dfr(as.character)
  data_vars_1 <-     headers_1$data_vars

  col_header_df_2 <- headers_2$col_header_df %>% map_dfr(as.character)
  row_header_df_2 <- headers_2$row_header_df %>% map_dfr(as.character)
  data_vars_2 <-     headers_2$data_vars

  col_header_df_temp <-  bind_rows(col_header_df_2,col_header_df_1) %>% filter(complete.cases(.)) %>% unique()
  row_header_df_temp <-  bind_rows(row_header_df_2,row_header_df_1) %>% filter(complete.cases(.)) %>% unique()

  table_constructor(
    df = original_data,
    col_header_df = col_header_df_temp,
    row_header_df = row_header_df_temp,data_vars = data_vars_1)

}
```



```{r cars, message=FALSE, warning=FALSE}
table1 <-
  student_df %>%
  mmtable(table_data = value)  +
  header_top(student) +
  header_top_left(grade) +
  header_left(class) +
  header_left_top(subject)

table1.1 <-
  student_df_1 %>%
  mmtable(table_data = value)  +
  header_top(student) +
  header_top_left(grade) +
  header_left(class) +
  header_left_top(subject)

table2 <-
  student_df_2 %>%
  mmtable(table_data = value)  +
  header_top(student) +
  header_top_left(grade) +
  header_left(class) +
  header_left_top(subject)

table1             +  table_title("Single Table")
table1 / table1.1  +  table_title("Table Quotient")
table1 * table1.1  +  table_title("Table Product")
table1 + table2    +  table_title("Table Sum")
```

