---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r message=FALSE, warning=FALSE, include=FALSE}

library(dplyr)
library(tidyr)
library(purrr)
library(magrittr)
library(broom)
library(tibble)
library(gapminder)
library(stringr)
library(htmltools)
library(xml2)
library(zoo)
library(gapminder)
library(webshot)
library(gt)
library(mmtable2)
```

```{r echo=FALSE, message=FALSE, warning=FALSE,error=FALSE, out.width = "600px", paged.print=FALSE}
gm_df <- gapminder_mm %>% filter(var != "Life expectancy")

gm_table_merged <- 
 gm_df %>% 
  mmtable(table_data = value) +
  header_left(year) +
  header_top(country) +
  header_left_top(var)  +
  header_top_left(continent)  +
  header_merged_cols()

# gm_table_merged %>% apply_formats() %>%  attr("merged_col_html")

gm_table_merged %>% print()
### PLAN - apply formats alsoways creates html, sends it to viewer, returns html

```



```{r echo=FALSE, message=FALSE, warning=FALSE,error=FALSE, out.width = "600px", paged.print=FALSE}
 
gm_df <- gapminder_mm %>% filter(var != "Life expectancy")

gm_table_merged <-
 gm_df %>%
  mmtable(table_data = value) +
  header_left(year) +
  header_top(country) +
  header_left_top(var)  +
  header_top_left(continent)

# gm_table_merged %>% apply_formats() %>%  attr("merged_col_html")
gm_table_merged %>% print()
### PLAN - apply formats alsoways creates html, sends it to viewer, returns html

```
